#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# SPDX-License-Identifier: BSL-1.0
#
# Generates test vectors for Karatsuba multiplication.
# Each test case consists of two operands and their product, represented as
# arrays of 64-bit limbs in little-endian order (matching big_int's internal layout).
#
# Usage: python3 generate_karatsuba_test_data.py

import random

LIMB_BITS = 64
LIMB_MAX = (1 << LIMB_BITS) - 1


def int_to_limbs(n: int) -> list[int]:
    """Convert a non-negative Python int to a list of 64-bit limbs (little-endian)."""
    if n == 0:
        return [0]
    limbs = []
    while n > 0:
        limbs.append(n & LIMB_MAX)
        n >>= LIMB_BITS
    return limbs


def format_limb_array(limbs: list[int], name: str) -> str:
    """Format a limb list as a C++ constexpr std::array initializer."""
    entries = ", ".join(f"0x{limb:016X}ULL" for limb in limbs)
    return f"    constexpr std::array<uint_multiprecision_t, {len(limbs)}> {name} = {{{{{entries}}}}};"


def generate_test_case(name: str, a: int, b: int) -> str:
    """Generate a full C++ test case for a * b."""
    assert a >= 0 and b >= 0
    product = a * b

    a_limbs = int_to_limbs(a)
    b_limbs = int_to_limbs(b)
    p_limbs = int_to_limbs(product)

    lines = [
        f"TEST(Multiplication, {name}) {{",
        format_limb_array(a_limbs, "a_limbs"),
        format_limb_array(b_limbs, "b_limbs"),
        format_limb_array(p_limbs, "expected_limbs"),
        "",
        "    const big_int a(std::from_range, a_limbs);",
        "    const big_int b(std::from_range, b_limbs);",
        "    const big_int expected(std::from_range, expected_limbs);",
        "",
        "    EXPECT_EQ(a * b, expected);",
        "    EXPECT_EQ(b * a, expected);  // commutativity",
        "}",
    ]
    return "\n".join(lines)


def random_n_limb(n: int) -> int:
    """Generate a random number with exactly n limbs (top limb nonzero)."""
    value = 0
    for i in range(n):
        value |= random.getrandbits(LIMB_BITS) << (i * LIMB_BITS)
    # Ensure top limb is nonzero
    top = random.randint(1, LIMB_MAX)
    value = (value & ((1 << ((n - 1) * LIMB_BITS)) - 1)) | (top << ((n - 1) * LIMB_BITS))
    return value


def main():
    random.seed(42)  # deterministic

    cases = []

    # Case 1: Both operands exactly at the Karatsuba cutoff (40 limbs)
    a = random_n_limb(40)
    b = random_n_limb(40)
    cases.append(generate_test_case("Karatsuba40x40", a, b))

    # Case 2: Both operands 50 limbs (well above cutoff)
    a = random_n_limb(50)
    b = random_n_limb(50)
    cases.append(generate_test_case("Karatsuba50x50", a, b))

    # Case 3: Mismatched sizes — 60 x 45 limbs (both above cutoff)
    a = random_n_limb(60)
    b = random_n_limb(45)
    cases.append(generate_test_case("Karatsuba60x45", a, b))

    # Case 4: Large squaring — 50 limbs squared
    a = random_n_limb(50)
    cases.append(generate_test_case("KaratsubaSquare50", a, a))

    # Case 5: Power-of-two-ish — (2^3200 - 1) * (2^3200 - 1)
    # This is all-ones in 50 limbs
    a = (1 << 3200) - 1
    b = (1 << 3200) - 1
    cases.append(generate_test_case("KaratsubaAllOnes50", a, b))

    print("// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception")
    print("// SPDX-License-Identifier: BSL-1.0")
    print("//")
    print("// Auto-generated by generate_karatsuba_test_data.py — do not edit manually.")
    print()
    print('#include <array>')
    print('#include <cstdint>')
    print()
    print('#include <gtest/gtest.h>')
    print()
    print('#include <beman/big_int/big_int.hpp>')
    print()
    print("using beman::big_int::big_int;")
    print("using beman::big_int::uint_multiprecision_t;")
    print()
    for case in cases:
        print(case)
        print()


if __name__ == "__main__":
    main()
